# https://grafana.com/docs/tempo/latest/configuration/#storage

server:
  http_listen_port: 3200 # nginx:4318
  grpc_listen_port: 9195 # default 9095 から変更する

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: :5317
        http:
          endpoint: :5318

compactor:
  compaction:
    block_retention: 48h # configure total trace retention here

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: linux-microservices
  storage:
    path: /mnt/data/tempo/generator/wal
    remote_write:
      - url: http://localhost:9009/api/v1/push
        send_exemplars: true

storage:
  trace:
    backend: s3
    s3:
      bucket: grafana-traces-data
      endpoint: ${S3_ENDPOINT}
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
      forcepathstyle: true
      insecure: false
      enable_dual_stack: false
    wal:
      path: /mnt/data/tempo/wal # where to store the wal locally
    local:
      path: /mnt/data/tempo/blocks
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
