server:
  http_listen_port: 4040
  grpc_listen_port: 9196  # default 9095 から変更する

storage:
  backend: s3
  s3:
    bucket_name: grafana-pyroscope-data
    endpoint: ${S3_ENDPOINT}
    access_key_id: ${S3_ACCESS_KEY}
    secret_access_key: ${S3_SECRET_KEY}

memberlist:
  bind_port: 7947
