version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - /mnt/data/grafana:/var/lib/grafana
      - /opt/grafana/provisioning:/etc/grafana/provisioning
    restart: always

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    network_mode: host
    ports:
      - 9009:9009
    volumes:
      - /opt/mimir:/etc/mimir
    command:
      - "-target=all"
      - "-config.file=/etc/mimir/mimir.yaml"
    restart: always
    environment:
      - OCI_AUTH
      - MIMIR_S3_ENDPOINT
      - MIMIR_S3_BUCKET_NAME
      - MIMIR_S3_S3FORCEPATHSTYLE
