version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - /mnt/data/grafana:/var/lib/grafana
      - /opt/grafana/provisioning:/etc/grafana/provisioning
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    ports:
      - 9090:9090
    volumes:
      - /mnt/data/prometheus:/prometheus
      - /opt/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=180d"
    restart: always

  # https://grafana.com/docs/mimir/latest/get-started/
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    network_mode: host
    ports:
      - 9009:9009
    volumes:
      - /opt/mimir:/etc/mimir
    command:
      - "-target=all"
      - "-config.file=/etc/mimir/mimir.yml"
    restart: always
    environment:
      - OCI_AUTH
      - MIMIR_S3_ENDPOINT
