version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      # /etc/grafana/provisioning/
      # /etc/grafana/grafana.ini
      - /mnt/data/grafana:/var/lib/grafana
      - /opt/grafana/provisioning:/etc/grafana/provisioning
      # letsencrypt
      - /mnt/data/letsencrypt:/etc/letsencrypt
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    ports:
      - 9090:9090
    volumes:
      # /etc/prometheus/prometheus.yml
      - /mnt/data/prometheus:/prometheus
      - /opt/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=180d"
    restart: always
