server:
  log_level: info
  http_listen_address: "0.0.0.0"
  http_listen_port: 4040

storage:
  backend: filesystem
  filesystem:
    path: /var/lib/pyroscope

scrape_configs:
  - job_name: "pyroscope"
    static_configs:
      - targets: ["localhost:4040"]
